# Code/Astro Diagnostic

Hello, and welcome to the Code/Astro diagnostic assignment! Code/Astro classes will assume familiarity with many foundational Python concepts, so we made this notebook to help you self-assess how helpful the workshop will be for you. Don't worry about getting everything right. Feel free to use the internet (online Python tutorials, etc.) to help you complete this diagnostic. If you understand every exercise here, even if you didn't get some of them the first time, you're prepared for Code/Astro.

Don't spend more than a few minutes on each exercise; if you can't figure it out after 15 minutes, it's time to move on or ask for help! Aim to spend no more than 90 minutes on the assignment in total. More challenging questions in each section are marked with an asterisk (*). Come back to those after you've completed all the other questions. Feel free to check out our solution set [here](https://colab.research.google.com/drive/1ZctFSkoE0uorM13Js-Djco09ve_7LOEh?usp=sharing) if you get really stuck.

If you have questions about the diagnostic, raise an issue (click "new issue" on the top right) on [the Code/Astro GitHub page](https://github.com/semaphoreP/codeastro/issues).

We also encourage you to read through [this twitter thread](https://twitter.com/SarahCBlunt/status/1375428263602909185?s=20) to learn about the motivation for this assignment.

### I: Types and Variables

**1.1.** Python is an object-oriented language, meaning that everything (even basic types like `int`s and `str`s) are represented as objects. Describe and give an example of each of the following types. The first is completed for you.

- `int`: integers (no decimals). Example: 345
- `str`
- `float`
- `tuple`
- `dict`
- `bool`
- `numpy.array`

**1.2.** Identify the types of the following Python objects (one per line). The first is completed for you.

In [ ]:
"foo"   # type str
1.2
{"foo": 1, "bar": 6}
100
'bar'
(1, 2, 3)
1e4
6 + 1.2

**1.3.** Check your work using the `type()` function. An example is below.

In [ ]:
print(type(True))

**1.4.** What is the `type` of the object `foo` in the code snippet below? Comment the fourth line in to check.

In [ ]:
def foo(bar):
    return bar

# type(foo)

**1.5.** What is the `type` of the variable `foo` in the code snippet below?

In [ ]:
foo = 5 + 3.4

**1.6** Access the first element of the following array, and assign it to the variable `foo`.

In [ ]:
import numpy as np

my_arr = np.array([1, 2, 3])

**1.7.** Access the value with key `foo` in the following dictionary, and assign it to the variable `bar`.

In [ ]:
my_dict = {'foo': 1, 'bar': 2}

**(*) 1.8**. Think through the following code. What do you expect `bar` to be at the end? Comment in the last line in the cell below and see if you were right.

Note: [this blog post](https://medium.com/@meghamohan/mutable-and-immutable-side-of-python-c2145cf72747) is a good overview of what's going on here.

In [ ]:
foo = [1, 2, 3]
bar = foo
foo.pop() # removes the last element of the list
# print(bar)

3

### II: Conditionals

**2.1** Write a piece of code that prints "positive" if ``x`` is greater than 0, "negative" if ``x`` is less than 0, and "0" if ``x`` is 0.

In [ ]:
x = 5

# your code here

**2.2** Write a piece of code that adds 5 to the variable ``x`` until ``x`` is equal to 20.

**2.3** Write a piece of code that loops over names in the list ``instructor_names`` and prints out "<<instructor's name>> is awesome!"

In [ ]:
instructor_names = ['Sarah', 'Jason', 'BJ']

# your code here

### III: Functions and Classes

**3.1** Define a function that takes in two integers and returns their product.

**(*) 3.2** Define a [recursive](https://realpython.com/python-thinking-recursively/#recursive-functions-in-python) function that computes the factorial of an integer. Test your function by computing 5! (the answer should be 120).

Let's define and play with a simple class. If you haven't seen classes before, and/or you're shaky on the concept of inheritance, we recommend reading through [this blog post](https://dev.to/oluchi/a-gentle-introduction-to-python-classes-for-newbies-p46) before continuing.

In [ ]:
class Numbers(object):
    """
    Class containing two floats that computes their product & sum.

    Args:
        a (float): number 1
        b (float): number 2
    """

    def __init__(self, a, b):
        self.a = a
        self.b = b

    def __repr__(self):
        return "The numbers {} and {}.".format(self.a, self.b)

    def num_sum(self):
        """
        Compute the sum of `a` and `b`

        Returns:
            float: sum of `a` and `b`
        """
        return self.a + self.b

    def num_prod(self):
        """
        Compute the product of `a` and `b`

        Returns:
            float: product of `a` and `b`
        """
        return self.a * self.b

myNumbers = Numbers(1, 2)
print(myNumbers)
my_sum = myNumbers.num_sum()

**3.3** Use the `Numbers` class to find the product of 100 and 350, and assign the result to the variable `my_prod`.

**(*) 3.4** Define a class `Integers` that inherits from `Numbers`. It should have an additional method, `fact_product` that computes the factorial of the product of two numbers. Instantiate your `Integers` class and compute the product of the factorial of 10 and 2 (you can use the function you defined in **3.2**).

**3.5** Args, kwargs, aaaarrrgh.... Take a look at the code below, then write a sentence or two explaining the difference between args (short for arguments) and kwargs (keyword arguments).

In [ ]:
def my_little_function(arg1, arg2, kwarg1=True, kwarg2='my cabbages!'):
  if kwarg1:
    print('Oh no, {}'.format(kwarg2))
  else:
    print(arg1 + arg2)

# your explanation here

**3.6** What do you expect ``my_little_function`` to print for each of the examples below? Write out your expectations, then comment in the function calls to check.

In [ ]:
args = [1, 2]
kwargs = {'kwarg1': False, 'kwarg2':'your cabbages?'}
other_kwargs = {'kwarg2':'whose cabbage is it anyway?'}

#my_little_function(*args)
#
# write your expectation here
#

my_little_function(*args, **kwargs)
#
# write your expectation here
#

# my_little_function(*args, **other_kwargs)
#
# write your expectation here
#

# my_little_function(**kwargs)
#
# write your expectation here
#

3


### IV. Imports

**4.1** Consider the following line of code:

``import scipy.ndimage``

Using this line of code as an example, explain the difference between packages and modules. Do all packages need modules and do all modules need packages?

**4.2** I want to use the following functions from python's `math` module: `sqrt`, `sin`, `cos`, `tan`. Write a single line of code that imports all four of these functions (there are multiple solutions). Note that it is not recommended to use the wildcard `*` when importing as it often imports many other variables, which can have unintended consequences!

**4.3** Import the package `numpy` as the variable `np` and evaluate sin(0.5) using the `sin` function available in both `math` and  `numpy`.  Do they agree?

0.479425538604203
0.479425538604203


### V: String Formatting

**5.1** Use string formatting to print out the randomly generated number stored in the variable `rand` to 5 decimal places. For example, if the random number is 0.12984737, the output should be `0.12985`. In the code below, we have already generated the random number for you.

In [ ]:
import random
rand = random.random()

# print something here

**5.2** Use string formatting to print out your python version and your python executable directory. We have stored your python executable directory in `python_dir`, your python major version number in `python_version_major`, and your python minor version number in `python_version_minor`. For example, if my python executable is in `/home/codeastro/anaconda3`, my python major version number is `3`, and my python minor version number is `8`, I should print out the following:

`Python 3.8 can be run from /home/codeastro/anaconda3 folder`

In [ ]:
import sys
python_dir = sys.prefix
python_version_major = sys.version_info.major
python_version_minor = sys.version_info.minor

### print something here

### VI: Lists

Here are three different ways to construct a list

1. Within a loop
1. Using list comprehension (see https://www.pythonforbeginners.com/basics/list-comprehensions-in-python)
1. Using the multiplication property of lists (see https://thehelloworldprogram.com/python/python-list-operations/)

First, lets create a 100-element long list filled with zeros using a for loop

In [ ]:
zeros = []
for i in range(100):
    zeros.append(0)

**6.1** Now use list multiplication to create the same 100-element long list filled with zeros

**(*) 6.2** Use list comprehension to create a list containing all even numbers between 0 and 100 with a single line of code.

As you saw in exercise 6.1, list operators operate on the entire list, not on the individual elements.

**6.3** Add 1 to each element in the list. Save the modified list into a new variable called "ones"

### VII: Numpy Arrays

It is quite common in astronomy and many other applications to perform mathematical operations on each element of a list or array. Using the built-in Python list type forces you to loop over the items in the list and operate on the elements one at a time. Looping over long lists in Python is very slow and bad practice.

Using numpy arrays allows for operations to be performed on an entire array at once. In reality a loop is still happening, but the numpy team programmed the loop in C so that it is much much faster.

Numpy can do a lot more than vector operations. Its a large, powerful package that you will use very often. See https://numpy.org for more information.

This example illustrates the different behavior for the + operator for lists and arrays.

In [ ]:
import numpy as np

x = [1, 2, 3, 4, 5]
# lets divide each element by 2
for i in range(len(x)):
    x[i] /= 2

# Now lets do the same with a numpy array
x = np.array([1, 2, 3, 4, 5])
x = x / 2

# See how easy!

# We can also create arrays with more than one dimension
# this creates a 3D array with shape 10 rows by 12 columns
arr = np.zeros((10, 12))

# use the .shape attribute of the array to check the shape
print(arr.shape)

# We can use indexing and slicing to extract and/or operate on a subset of an array
# see https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/
# lets add 1 to the single element that is in the 0th position in both the rows and columns
arr[0, 0] = 1

# now add 10 to everything in the in the 0th row (first dimension)
arr[0, :] += 10
# now everything in the 10th column (second dimension)
arr[:, 10] += 10
# now every other element in the 4th row
arr[4, ::2] += 10

print(arr)

(10, 12)
[[11. 10. 10. 10. 10. 10. 10. 10. 10. 10. 20. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [10.  0. 10.  0. 10.  0. 10.  0. 10.  0. 20.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]]


**7.1** Create a 9x9 array filled with 1 in every element. Hint: there is a `np.ones` function too.

**7.2** Multiply every element in the 0th row by 100 using slicing

Your array should now look like this:

[[100. 100. 100. 100. 100. 100. 100. 100. 100.] \\
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.] \\
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.] \\
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.] \\
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.] \\
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.] \\
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.] \\
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.] \\
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.]]

**(*) 7.3** Extract every 3rd element from the 4th column of the array that you created in step 6.2

**7.4** Reshape the array into a 1-dimensional vector

**7.5** Modify the 4th element of the vector ``x``, defined below. Change the value to 20.

In [ ]:
x = np.array([0, 1, 2, 3, 4, 5, 6])
y = x

**7.6** Print the 4th element of the vector y. Was y also modified as a result of modifying x?

If I wanted to loop over the lines of a file and append each line to a list but I don't know how many lines are in the file, would it be more appropriate to use a list or an array? Check out [this post](https://www.geeksforgeeks.org/difference-between-list-and-array-in-python/) for a quick arrays vs lists reference.

If I needed to calculate the square root of 10000 numbers would it be better to use a list or an array?

### VIII: Dictionaries

**8.1** Construct a dictionary where the keys are the elements of the `lorem` list below and the values are the 2nd character in each word. First construct this dictionary using a loop, then construct the same dictionary using dictionary comprehension. See here https://www.geeksforgeeks.org/python-dictionary-comprehension/ for dictionary comprehension syntax.

In [ ]:
lorem = ['Lorem', 'ipsum', 'dolor', 'sit', 'amet,', 'consectetur',
         'adipiscing', 'elit,', 'sed', 'do', 'eiusmod', 'tempor',
         'incididunt', 'ut', 'labore', 'et', 'dolore', 'magna', 'aliqua.']

**8.2** Update the values to 0 for the following keys without using a loop. Hint: lookup the `update` method for Python dictionaries

In [ ]:
changes = ['dolor', 'elit', 'tempor', 'magna']

**8.3** Loop over the key value pairs and print each pair in the following format `<key>: <value>`

**8.4** Remove all key/value pairs where the value is "o"

### IX: Plotting with matplotlib

**9.1** Initialize a figure using ``matplotlib``. Plot ``x`` vs ``y`` as a black solid line, and ``x`` vs ``z`` as a scatterplot on the same figure.

In [ ]:
import matplotlib.pyplot as plt

x = np.arange(10)
y = np.arange(10)
z = np.arange(10) + 1

# your code here

**9.2** Make the y axis of your plot above log-scale. Add x- and y-axis labels. Add a legend. Change the color and size of the markers used for the scatterplot.